### PR TITLE
SUSE SAP HA Yast wizard for HANA doesn´t configure the HANA hooks.

### PR DESCRIPTION
**Pull request by varkoly**

### CODE REVIEW

**Comment by lslezak** [comment]
Looks OK, just the SP3 fix also contains a change in the `test/test_helper.rb` file : https://github.com/yast/yast-sap-ha/pull/8/files#diff-ba37813ca277c227a74a372479b7b05b7f3ff085d890ab708f80d62573efdb7a

That is not needed in `master`?

**Comment by varkoly** [comment]
> Looks OK, just the SP3 fix also contains a change in the `test/test_helper.rb` file : https://github.com/yast/yast-sap-ha/pull/8/files#diff-ba37813ca277c227a74a372479b7b05b7f3ff085d890ab708f80d62573efdb7a
> 
> That is not needed in `master`?

You've right. It is needed. Now I've added the required changes.

**Review by lslezak — APPROVED** [review]
LGTM

**Comment by varkoly** [comment]
>That is not needed in master?
In master this is already fixed.

Dipl.-Ing. Péter Varkoly

SUSE Software Solutions Frankenstraße 146

90461 Nürnberg, Germany

Geschäftsführer: Ivo Totev, Andrew Myers, Andrew McDonald, Boudien Moerman

(HRB 36809, AG Nürnberg)

Am 28.03.2022 um 16:46 schrieb Ladislav Slezák ***@***.***>:

﻿

Looks OK, just the SP3 fix also contains a change in the test/test_helper.rb file : https://github.com/yast/yast-sap-ha/pull/8/files#diff-ba37813ca277c227a74a372479b7b05b7f3ff085d890ab708f80d62573efdb7a

That is not needed in master?

**Pull request merged**
